"""
Google Takeout Metadata Embedder
--------------------------------

Embeds photoTakenTime from Google's JSON sidecar files into image/video EXIF/metadata.

Handles multiple file naming edge-cases generated by Google Takeout:
  - Standard:          photo.jpg.supplemental-metadata.json
  - Duplicates:        photo.jpg.supplemental-metadata(1).json
  - Truncated suffix:  photo.jpg.su.json  /  photo.jpg..json
  - Double extension:  photo.jpg.jpg.supplemental-metadata.json
  - Edited variants:   photo-edited.jpg  ->  photo.jpg.supplemental-metadata.json
  - Bare JSON:         photo.json  (Files from the internet)
  - Name-truncated:    photo_very_long_name.jpg -> photo_very_long_nam.json

Requirements:
  - Python 3.7+
  - ExifTool installed and available on PATH (https://exiftool.org)
"""

import os
import json
import re
import subprocess
import sys
import datetime
import argparse
from pathlib import Path

# -----------------------------------------------------------------------------
# CONSTANTS
# -----------------------------------------------------------------------------

IMAGE_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.gif', '.webp',
                    '.tif', '.tiff', '.heic', '.bmp'}
VIDEO_EXTENSIONS = {'.mp4', '.mov', '.3gp', '.mpg', '.mpeg', '.m4v'}
ALL_EXTENSIONS   = IMAGE_EXTENSIONS | VIDEO_EXTENSIONS

# All known truncations of ".supplemental-metadata" that Google produces.
# Sorted longest-first so the most specific match is tried first.
SUPPLEMENTAL_SUFFIXES = [
    ".supplemental-metadata",
    ".supplemental-metadat",
    ".supplemental-metada",
    ".supplemental-metad",
    ".supplemental-meta",
    ".supplemental-met",
    ".supplemental-me",
    ".supplemental-m",
    ".supplemental-",
    ".supplemental",
    ".supplemen",
    ".supple",
    ".suppl",
    ".supplement",
    ".su",
    ".s",
    ".",    # extreme truncation: photo.jpg..json
]

# -----------------------------------------------------------------------------
# METADATA FINDER
# -----------------------------------------------------------------------------

def glob_escape(s):
    """Escape glob special characters so they can be used in Path.glob()."""
    return re.sub(r'([\[\]*?])', r'[\1]', s)


def find_json(photo: Path):
    """
    Finds the correct Google Takeout JSON metadata file for a given photo.
    Returns the Path of the first match, or None.
    """
    folder = photo.parent
    name   = photo.name
    ext    = photo.suffix
    stem   = photo.stem

    candidates = []

    # 1. Standard supplemental-metadata variants
    for suffix in SUPPLEMENTAL_SUFFIXES:
        candidates.append(folder / f"{name}{suffix}.json")
        candidates.append(folder / f"{name}{suffix}(1).json")
        candidates.append(folder / f"{name}{suffix}(2).json")
        # Double-extension edge case
        candidates.append(folder / f"{name}{ext}{suffix}.json")

    # 2. Bare .json sidecar (no supplemental-metadata suffix)
    candidates.append(folder / f"{stem}.json")

    # 3. Fuzzy glob - handles cases where the JSON name starts with the full media filename.
    try:
        safe = glob_escape(name)
        for f in folder.glob(f"{safe}*.json"):
            candidates.append(f)
        if len(name) > 40:
            safe40 = glob_escape(name[:40])
            for f in folder.glob(f"{safe40}*.json"):
                candidates.append(f)
    except Exception:
        pass

    # 4. Reverse-truncation: JSON name is shorter than media name due to filesystem limits.
    if len(name) > 20:
        try:
            for trim in range(1, 9):
                short_stem = stem[:-trim]
                if not short_stem:
                    break
                candidates.append(folder / f"{short_stem}.json")
                safe_short = glob_escape(short_stem)
                for f in folder.glob(f"{safe_short}*.json"):
                    candidates.append(f)
        except Exception:
            pass

    # 5. Strip -edited / (N) suffix to match base file's JSON
    base_stem = re.sub(r'(?:-edited|[\s_-]?\(\d+\))$', '', stem, flags=re.IGNORECASE).strip()
    if base_stem and base_stem != stem:
        base_name = base_stem + ext
        for suffix in SUPPLEMENTAL_SUFFIXES:
            candidates.append(folder / f"{base_name}{suffix}.json")
            candidates.append(folder / f"{base_name}{suffix}(1).json")
        candidates.append(folder / f"{base_stem}.json")

    # Deduplicate and return first existing match
    seen = set()
    for c in candidates:
        if c in seen:
            continue
        seen.add(c)
        if c.exists():
            return c

    return None

def get_timestamp(meta: dict):
    """
    Extract the best Unix timestamp string from Google's JSON metadata.
    Returns None if no valid timestamp is found.
    """
    for key in ("photoTakenTime", "creationTime"):
        entry = meta.get(key, {})
        ts = entry.get("timestamp")
        if ts and str(ts) not in ("0", "", "null"):
            try:
                int(ts)
                return str(ts)
            except (ValueError, TypeError):
                continue
    return None

# -----------------------------------------------------------------------------
# EXIFTOOL EXECUTION
# -----------------------------------------------------------------------------

def ts_to_exif(unix_ts: str) -> str:
    """Convert a Unix timestamp string to ExifTool date format: YYYY:MM:DD HH:MM:SS."""
    dt = datetime.datetime.fromtimestamp(int(unix_ts), tz=datetime.timezone.utc)
    return dt.strftime("%Y:%m:%d %H:%M:%S")

def build_cmd(photo: Path, timestamp: str, dry_run: bool):
    """Build the exiftool command list to embed a timestamp into a file."""
    date_str = ts_to_exif(timestamp)
    is_video = photo.suffix.lower() in VIDEO_EXTENSIONS

    if is_video:
        tags = [
            f"-CreateDate={date_str}",
            f"-ModifyDate={date_str}",
            f"-TrackCreateDate={date_str}",
            f"-TrackModifyDate={date_str}",
            f"-MediaCreateDate={date_str}",
            f"-MediaModifyDate={date_str}",
        ]
    else:
        tags = [
            f"-DateTimeOriginal={date_str}",
            f"-CreateDate={date_str}",
            f"-ModifyDate={date_str}",
        ]

    cmd = ["exiftool", "-m"]
    if not dry_run:
        cmd.append("-overwrite_original")
    cmd += tags
    cmd.append(str(photo))
    return cmd

# -----------------------------------------------------------------------------
# MAIN SCRIPT
# -----------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Embed Google Takeout metadata into media files.")
    parser.add_argument("folder", help="Path to the Google Takeout folder containing the media and JSON files.")
    parser.add_argument("--dry-run", action="store_true", help="Log output without modifying any files.")
    parser.add_argument("--process-trashed", action="store_true", help="Include files deleted from Google Photos (.trashed-*).")
    args = parser.parse_args()

    folder = Path(args.folder)

    if not folder.exists():
        print(f"ERROR: Folder not found: {folder}")
        sys.exit(1)

    try:
        ver_proc = subprocess.run(["exiftool", "-ver"], capture_output=True, text=True, check=True)
        print(f"ExifTool version: {ver_proc.stdout.strip()}")
    except FileNotFoundError:
        print("ERROR: exiftool not found on PATH.")
        print("Download from https://exiftool.org, and ensure it is available in your system's PATH.")
        sys.exit(1)

    if args.dry_run:
        print("\n[ DRY RUN MODE - NO FILES WILL BE MODIFIED ]\n")

    # Collect media files
    all_media = []
    for p in folder.rglob("*"):
        if not p.is_file():
            continue
        if p.suffix.lower() not in ALL_EXTENSIONS:
            continue
        if not args.process_trashed and p.name.startswith(".trashed"):
            continue
        all_media.append(p)

    total = len(all_media)
    print(f"Found {total} media files under {folder}\n")
    if total == 0:
        print("Nothing to process. Check your folder path.")
        sys.exit(0)

    updated = []
    no_json = []
    no_ts   = []
    failed  = []

    for i, photo in enumerate(sorted(all_media), 1):
        prefix = f"[{i:>5}/{total}]"

        json_path = find_json(photo)
        if not json_path:
            no_json.append(photo)
            print(f"{prefix} [SKIP] NO JSON FILE FOUND: {photo.name}")
            continue

        try:
            with open(json_path, encoding="utf-8") as f:
                meta = json.load(f)
        except Exception as e:
            failed.append((photo, f"JSON parse error: {e}"))
            print(f"{prefix} [FAIL] JSON PARSE ERROR FOR: {photo.name} - {e}")
            continue

        timestamp = get_timestamp(meta)
        if not timestamp:
            no_ts.append(photo)
            print(f"{prefix} [SKIP] NO TIMESTAMP DATA: {photo.name}")
            continue

        try:
            dt = datetime.datetime.fromtimestamp(int(timestamp), tz=datetime.timezone.utc)
            dt_str = dt.strftime("%Y-%m-%d %H:%M UTC")
        except Exception:
            dt_str = f"ts={timestamp}"

        if args.dry_run:
            updated.append(photo)
            print(f"{prefix} [DRY RUN] {photo.name} -> {dt_str}")
            continue

        cmd = build_cmd(photo, timestamp, dry_run=False)
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        except subprocess.TimeoutExpired:
            failed.append((photo, "ExifTool timed out"))
            print(f"{prefix} [FAIL] COMMAND TIMED OUT: {photo.name}")
            continue

        if result.returncode == 0:
            updated.append(photo)
            print(f"{prefix} [OK] {photo.name} -> {dt_str}")
        else:
            err = (result.stderr or result.stdout).strip()
            failed.append((photo, err))
            print(f"{prefix} [FAIL] EXIFTOOL ERROR: {photo.name} - {err}")

    # Display Summary
    print("\n-------------------------------------------------------------------------------")
    print("SUMMARY")
    print("-------------------------------------------------------------------------------")
    print(f"Updated successfully : {len(updated)}")
    print(f"No JSON sidecar      : {len(no_json)}")
    print(f"No valid timestamp   : {len(no_ts)}")
    print(f"Failed (ExifTool)    : {len(failed)}")
    
    if not args.process_trashed:
        trashed_count = sum(
            1 for p in folder.rglob("*")
            if p.is_file() and p.name.startswith(".trashed") and p.suffix.lower() in ALL_EXTENSIONS
        )
        if trashed_count:
            print(f"Skipped trashed items: {trashed_count} (Use --process-trashed to include)")
    print("-------------------------------------------------------------------------------")

    # Generate logs
    log_dir = Path.cwd()
    
    if no_json:
        p = log_dir / "log_no_json.txt"
        with open(p, "w", encoding="utf-8") as f:
            f.write("Files without matching JSON sidecar:\n\n")
            f.writelines(f"{item}\n" for item in no_json)
        print(f"Logged missing JSON items -> {p}")

    if failed:
        p = log_dir / "log_failed.txt"
        with open(p, "w", encoding="utf-8") as f:
            f.write("Files that failed processing in ExifTool:\n\n")
            for item, err in failed:
                f.write(f"{item}\n    Error: {err}\n\n")
        print(f"Logged failed items -> {p}")

    if no_ts:
        p = log_dir / "log_no_timestamp.txt"
        with open(p, "w", encoding="utf-8") as f:
            f.write("Files with JSON sidecar but no usable timestamp:\n\n")
            f.writelines(f"{item}\n" for item in no_ts)
        print(f"Logged items lacking timestamps -> {p}")

    print()
    if len(updated) == total:
        print("All files processed successfully! Ready for upload.")
    else:
        remaining = total - len(updated)
        print(f"{remaining} file(s) could not be updated - check the log files above.")


if __name__ == "__main__":
    main()
